const GAME_DATA = {
  stations: ["tatzpit","shomera","beitbad","gat","goren","bor"],
  creatures: {
    tatzpit:{emoji:"🌬️", he:{name:"אווירון", place:"התצפית", role:"שומר אוויר ההרים", contribution:"אוויר הרים צלול כיין"}, fr:{name:"Aviron", place:"le point de vue", role:"gardien de l’air des montagnes", contribution:"l’air pur des montagnes"}, image:"assets/characters/aviron.png", color:"#4bb7d2"},
    shomera:{emoji:"🛖", he:{name:"שומרון", place:"השומרה", role:"שומר האש והמעשנה", contribution:"טמפרטורת בישול מושלמת"}, fr:{name:"Shomeron", place:"la tour de garde", role:"gardien du feu et du fumoir", contribution:"la température parfaite"}, image:"assets/characters/shomeron.png", color:"#b88649"},
    beitbad:{emoji:"🫒", he:{name:"זייתון", place:"בית הבד", role:"שומר שמן הזית", contribution:"שמן הזית"}, fr:{name:"Zeiton", place:"le pressoir à olives", role:"gardien de l’huile d’olive", contribution:"l’huile d’olive"}, image:"assets/characters/zeiton.png", color:"#7fa13d"},
    gat:{emoji:"🍇", he:{name:"גתון", place:"הגת", role:"שומר היין", contribution:"היין לשתייה"}, fr:{name:"Gaton", place:"le pressoir à vin", role:"gardien du vin", contribution:"le vin"}, image:"assets/characters/gaton.png", color:"#7a44a0"},
    goren:{emoji:"🌾", he:{name:"דישון", place:"הגורן", role:"שומר החיטה", contribution:"הקמח ללחם"}, fr:{name:"Dishon", place:"l’aire de battage", role:"gardien du blé", contribution:"la farine du pain"}, image:"assets/characters/dishon.png", color:"#d99b24"},
    bor:{emoji:"💧", he:{name:"בורי", place:"בור המים", role:"שומר המים", contribution:"מי הגשמים"}, fr:{name:"Bori", place:"la citerne", role:"gardien de l’eau", contribution:"l’eau"}, image:"assets/characters/bori.png", color:"#4aaed1"}
  },
  ui: {
    he:{
      title:"שומרי התבלין", subtitle:"היצורים מחכים...", start:"התחילו במסע", lang:"שפה", storyTitle:"אוי לא...", story:["יצורי הגן נעלמו.","בלי יצורי הגן אי אפשר להשלים את התבלין הסודי.","ובלי התבלין הסודי...","אי אפשר להגיש את ארוחת הצהריים."], next:"המשך", rulesTitle:"חוקי המשחק", rules:["הסתובבו בגן.","מצאו תחנה.","סרקו את ה־QR.","ענו על השאלות ותתפסו יצורים.","טעיתם? תוכלו לנסות שוב.","אספו את כל היצורים לפני ארוחת הצהריים.","אולי גם תזכו בבונוס סודי..."], nameTitle:"איך קוראים לקבוצה?", namePlaceholder:"שם הקבוצה", begin:"צאו לדרך", map:"מפת ההתקדמות", creatures:"יצורים", stars:"כוכבים", bonuses:"בונוסים", time:"זמן", nextHideout:"מקום המסתור הבא", scanHint:"סרקו את קוד ה־QR בתחנה שאליה הוביל אתכם הרמז.", wrongStationTitle:"נראה שהגעתם למקום של שומר אחר...", wrongStationText:"חזרו לרמז האחרון וחפשו את מקום המסתור הבא.", alreadyTitle:"כבר מטייל איתכם", alreadyText:"אין צורך לאסוף אותו שוב. המשיכו למצוא את חבריו.", found:"מצאתם את מקום המסתור של", patient:"אפשר לחכות בסבלנות. הרבה סבלנות...", answerQuestions:"לענות על השאלות", wait:"נחכה בסבלנות...", waitResult:"נראה שהוא לא יוצא לבד. תצטרכו לענות על השאלות.", tryAgain:"ניסיון נוסף", correct:"נכון", continue:"המשך", captured:"הצטרף לאוסף שלכם!", backMap:"חזרה למפה", bonusTitle:"⭐ בונוס סודי!", bonusText:"הגעתם בדיוק לאחד מזמני התבלין הסודיים. אל תשאלו איך. השומרים לא מגלים.", endTitle:"כל הכבוד!", endLines:["הצלחתם לאסוף את כל שומרי התבלין.","התבלין הסודי הושלם.","אפשר להגיש את ארוחת הצהריים."], screenshot:"צלמו מסך ושלחו בקבוצה.", thanks:"תודה שביקרתם בגן התנ״כי ביד השמונה.", reset:"איפוס משחק", chooseLang:"בחרו שפה"},
    fr:{
      title:"Les Gardiens des Épices", subtitle:"Les créatures vous attendent...", start:"Commencer l’aventure", lang:"Langue", storyTitle:"Oh non...", story:["Les créatures du jardin ont disparu.","Sans elles, impossible de compléter l’épice secrète.","Et sans l’épice secrète...","impossible de servir le déjeuner."], next:"Continuer", rulesTitle:"Règles du jeu", rules:["Promenez-vous dans le jardin.","Trouvez une station.","Scannez le QR code.","Répondez aux questions et collectez les créatures.","Une erreur ? Vous pouvez réessayer.","Collectez toutes les créatures avant le déjeuner.","Peut-être découvrirez-vous aussi un bonus secret..."], nameTitle:"Nom de l’équipe", namePlaceholder:"Nom de l’équipe", begin:"C’est parti", map:"Carte de progression", creatures:"Créatures", stars:"Étoiles", bonuses:"Bonus", time:"Temps", nextHideout:"Prochaine cachette", scanHint:"Scannez le QR code à la station indiquée par l’indice.", wrongStationTitle:"On dirait que vous êtes chez un autre gardien...", wrongStationText:"Revenez au dernier indice et cherchez la prochaine cachette.", alreadyTitle:"vous accompagne déjà", alreadyText:"Inutile de le collecter à nouveau. Continuez à chercher ses amis.", found:"Vous avez trouvé la cachette de", patient:"Vous pouvez attendre patiemment. Très patiemment...", answerQuestions:"Répondre aux questions", wait:"Attendons un peu...", waitResult:"Il ne sortira pas tout seul. Il faudra répondre aux questions.", tryAgain:"Réessayer", correct:"Correct", continue:"Continuer", captured:"a rejoint votre collection !", backMap:"Retour à la carte", bonusTitle:"⭐ Bonus secret !", bonusText:"Vous êtes tombés exactement sur l’un des temps secrets de l’épice. Ne demandez pas comment. Les gardiens ne disent rien.", endTitle:"Bravo !", endLines:["Vous avez collecté tous les Gardiens des Épices.","L’épice secrète est complète.","Le déjeuner peut être servi."], screenshot:"Faites une capture d’écran et envoyez-la au groupe.", thanks:"Merci d’avoir visité le Jardin biblique de Yad HaShmona.", reset:"Réinitialiser", chooseLang:"Choisissez une langue"}
  },
  hints:{
    he:{tatzpit:"חפשו את המקום שבו הנוף והאוויר מוסיפים את המרכיב שאי אפשר להחזיק ביד.", shomera:"חפשו את המקום שממנו אפשר להשגיח על הכרם והמטע.", beitbad:"חפשו את המקום שבו הפכו זיתים לשמן.", gat:"חפשו את המקום שבו הענבים הפכו לתירוש וליין.", goren:"חפשו את המקום שבו הרוח עזרה להפריד בין גרעין למוץ.", bor:"חפשו את המקום שבו שמרו כל טיפת גשם לעונה היבשה."},
    fr:{tatzpit:"Cherchez l’endroit où le paysage et l’air apportent l’ingrédient qu’on ne peut pas tenir dans la main.", shomera:"Cherchez l’endroit d’où l’on surveillait la vigne et le verger.", beitbad:"Cherchez l’endroit où les olives devenaient de l’huile.", gat:"Cherchez l’endroit où les raisins devenaient du moût et du vin.", goren:"Cherchez l’endroit où le vent aidait à séparer le grain de la balle.", bor:"Cherchez l’endroit où l’on gardait chaque goutte de pluie pour la saison sèche."}
  }
};
const QUESTIONS = {
  he:{
    gat:[
      {text:"כיצד היה נהוג לדרוך את הענבים בגת?",answers:[{text:"עם סנדלים כדי לתת ארומה של אדמה",correct:false,feedback:"🍇 ארומה של סנדל היא לא בדיוק תו יין מבוקש..."},{text:"עם סנדלים כדי לרסק גם את החרצנים",correct:false,feedback:"🍇 דווקא את החרצנים השתדלו שלא לשבור, כדי לא להוסיף מרירות ליין."},{text:"יחפים, כדי למעוך את הענבים בלי לשבור את החרצנים",correct:true,feedback:""},{text:"היו משכיבים אדם בגת ודורכים עליו",correct:false,feedback:"🍇 אם כך היו מייצרים יין, כנראה שלא היה נשאר מי שישתה אותו..."}],explanation:"דריכה יחפה אפשרה למעוך את הענבים בלי לרסק את החרצנים, שעלולים להוסיף מרירות."},
      {text:"לאחר הדריכה, לאן זרם מיץ הענבים?",answers:[{text:"לבאר מים כדי לקרר אותו",correct:false,feedback:"🍇 באר מים נועדה למים, לא לתירוש."},{text:"לכלי חרס שהוטמן באדמה",correct:false,feedback:"🍇 כלי חרס יכולים לשמש לאחסון, אבל קודם התירוש צריך לזרום אל בור האיגום."},{text:"דרך תעלה אל בור איגום",correct:true,feedback:""},{text:"אל בית הבד",correct:false,feedback:"🍇 בית הבד שייך לזיתים. גתון מבקש סדר."}],explanation:"התירוש זרם ממשטח הדריכה דרך תעלה אל בור איגום, ושם נאסף להמשך התהליך."},
      {text:"למה ייצרו יין כמעט בכל כפר?",answers:[{text:"כי לא ידעו לשתות מים",correct:false,feedback:"🍇 הם בהחלט ידעו לשתות מים. יין היה חלק חשוב מהתרבות, הטקסים והמסחר."},{text:"כי היין היה זול יותר ממים",correct:false,feedback:"🍇 יין דרש כרמים, בציר, דריכה ותסיסה. זול יותר זה לא הסיפור."},{text:"כי היין היה משקה בסיסי, טקסי ומסחרי",correct:true,feedback:""},{text:"כי התורה אסרה לשתות מים בחגים",correct:false,feedback:"🍇 התורה לא אסרה לשתות מים בחגים."}],explanation:"יין היה חלק מחיי היום־יום, מטקסים, מארוחות וממסחר."},
      {text:"כמה ענבים בערך נדרשים להפקת ליטר יין?",answers:[{text:"שני ענבים",correct:false,feedback:"🍇 רגע... איך בדיוק משני ענבים ייצא ליטר יין?"},{text:"בערך קילוגרם וחצי",correct:true,feedback:""},{text:"עשרים קילוגרם",correct:false,feedback:"🍇 עשרים קילו? זה כבר נשמע כמו יין שמתבייש לצאת."},{text:"אשכול אחד בדיוק",correct:false,feedback:"🍇 גם אשכול אחד לא יספיק לליטר יין."}],explanation:"ליטר יין דורש בדרך כלל בערך קילוגרם וחצי ענבים, תלוי בזן ובתהליך."}
    ],
    shomera:[
      {text:"מה הייתה המטרה העיקרית של השומרה?",answers:[{text:"מגורים קבועים של משפחה חקלאית",correct:false,feedback:"🛖 משפחה שלמה? קצת צפוף שם..."},{text:"מקום לאחסון תבואה במשך כל השנה",correct:false,feedback:"🌾 לאחסון תבואה היו מחסנים ואסמים. השומרה נועדה לשמירה בשטח."},{text:"נקודת תצפית ומגורים זמניים לשמירה על הכרם או המטע",correct:true,feedback:""},{text:"בסיס צבאי של הצבא הרומי",correct:false,feedback:"🏛️ אם הרומאים היו בונים כאן בסיס, הוא היה נראה קצת יותר גדול..."}],explanation:"השומרה שימשה את החקלאי בעונת היבול לתצפית, שמירה ולינה זמנית."},
      {text:"מדוע השומרה נבנתה בדרך כלל במקום גבוה?",answers:[{text:"כדי להיות קרובה יותר לעננים",correct:false,feedback:"🛖 עננים זה יפה, אבל השומרה צריכה לראות את השטח."},{text:"כדי להתרחק מחרקים",correct:false,feedback:"🛖 חרקים יש גם למעלה, לצערנו."},{text:"כדי לראות למרחק ולהשגיח על השטח",correct:true,feedback:""},{text:"כדי שהרוח תייבש את הענבים",correct:false,feedback:"🛖 מה פתאום ענבים? הרוח כאן עסוקה בלייבש את הכביסה."}],explanation:"מקום גבוה איפשר תצפית טובה והגנה על היבול."},
      {text:"מי היה האויב הגדול של החקלאי בזמן הבציר?",answers:[{text:"רק חיילים זרים",correct:false,feedback:"🛖 חיילים זרים הם לא הבעיה היומיומית בכרם."},{text:"רק חיות בר",correct:false,feedback:"🛖 חיות בר זה כיוון טוב, אבל זו לא הסיבה היחידה שבנו שומרה."},{text:"גנבים וגם בעלי חיים שחיפשו מזון",correct:true,feedback:""},{text:"דבורים ששתו את מיץ הענבים",correct:false,feedback:"🐝 גם אם הדבורים אוהבות מתוק, הן לא הסיבה שבנו שומרה."}],explanation:"החקלאי שמר על היבול גם מגנבים וגם מבעלי חיים."},
      {text:"איזה ביטוי מקראי מתאר מקום שמירה בכרם?",answers:[{text:"עיר בצורה",correct:false,feedback:"🏰 עיר בצורה נועדה להגן על עיר שלמה, לא על כרם קטן."},{text:"ארמון המלך",correct:false,feedback:"👑 ארמון המלך קצת מפואר מדי בשביל שומרה..."},{text:"סוכה בכרם",correct:true,feedback:""},{text:"בית היין",correct:false,feedback:"🍇 בית היין שייך לגתון. שומרון שומר על הכרם, לא על היין."}],explanation:"הביטוי 'סוכה בכרם' מתאים למבנה שמירה זמני בשטח חקלאי."}
    ],
    goren:[
      {text:"מה עשו בגורן?",answers:[{text:"ייצרו יין",correct:false,feedback:"🌾 יין? זה נשמע כמו העבודה של גתון."},{text:"הפרידו את גרעיני הדגן מהמוץ",correct:true,feedback:""},{text:"כבשו זיתים לשמן",correct:false,feedback:"🌾 זיתים בבית הבד, לא כאן."},{text:"חצבו קברים",correct:false,feedback:"🌾 קברים? זה כבר סיור אחר לגמרי."}],explanation:"בגורן הפרידו את גרעיני הדגן מן המוץ והקש."},
      {text:"למה הגורן צריכה להיות במקום פתוח וחשוף לרוח?",answers:[{text:"כדי שהרוח תעיף את המוץ הקל ותשאיר את הגרעינים",correct:true,feedback:""},{text:"כדי שהחיטה תתבשל בשמש",correct:false,feedback:"🌾 חיטה לא מתבשלת בשמש. היא צריכה דיש, זרייה וטחינה."},{text:"כדי שהעובדים לא יירדמו",correct:false,feedback:"🌾 אם העובדים נרדמו, זו כבר בעיית ניהול."},{text:"כדי לקרוא לעופות לבוא לאכול",correct:false,feedback:"🌾 עופות אולי היו שמחים, אבל החקלאים פחות."}],explanation:"בזרייה הרוח מעיפה את המוץ הקל, והגרעינים הכבדים נשארים קרובים."},
      {text:"מהו דיש?",answers:[{text:"דריכת ענבים ברגליים",correct:false,feedback:"🌾 דריכת ענבים שייכת לגת. דישון נשאר עם הדגן."},{text:"ריסוק זיתים באבן",correct:false,feedback:"🌾 זיתים בבית הבד, לא כאן."},{text:"הפרדת הגרעינים מהשיבולים באמצעות דריכה או מורג",correct:true,feedback:""},{text:"טבילה במקווה",correct:false,feedback:"🌾 מקווה זו ליגה אחרת של קדושה."}],explanation:"דיש הוא פעולת הפרדת הגרעינים מן השיבולים, לעיתים בעזרת מורג או דריכה."},
      {text:"מהו מוץ?",answers:[{text:"גרעין החיטה הטוב",correct:false,feedback:"🌾 דווקא את הגרעין רצו לשמור."},{text:"החלקים הקלים והיבשים שנפרדים מהדגן",correct:true,feedback:""},{text:"שם קדום ללחם",correct:false,feedback:"🍞 אם זה היה שם קדום ללחם, כנראה שהאופים היו מתבלבלים..."},{text:"תבלין חריף מתקופת המקרא",correct:false,feedback:"🌶️ מוץ אולי עף ברוח, אבל חריף הוא ממש לא."}],explanation:"המוץ הוא החלק הקל והיבש שמופרד מן הדגן בתהליך העיבוד."}
    ],
    bor:[
      {text:"למה בורות מים היו חשובים במיוחד בהרי יהודה?",answers:[{text:"כי כל יישוב היה על שפת אגם",correct:false,feedback:"💧 אגם ליד כל יישוב? זה היה מקל על כולם, אבל לא."},{text:"כי באזור ההר אין תמיד מעיינות זמינים בכל מקום",correct:true,feedback:""},{text:"כי אסור היה לשתות ממעיינות",correct:false,feedback:"💧 דווקא מעיינות היו מקור מים מצוין כשאפשר היה להגיע אליהם."},{text:"כי מים עתיקים טעימים יותר",correct:false,feedback:"💧 מים מיושנים אולי מתאימים ליין... לא לשתייה."}],explanation:"באזור ההר לא בכל מקום יש מעיין זמין, ולכן אגירת מי גשמים הייתה חיונית."},
      {text:"מה מונע מהמים לחלחל החוצה מן הבור?",answers:[{text:"טיח אטום על הדפנות",correct:true,feedback:""},{text:"שכבת צמר כבשים",correct:false,feedback:"🐑 צמר אולי מחמם בחורף, אבל הוא לא אוטם בור מים."},{text:"מלח גס בתחתית",correct:false,feedback:"🧂 מלח לא אוטם בורות מים, והוא גם היה מקלקל את המים."},{text:"שומרים שעמדו וסגרו חורים עם האצבע",correct:false,feedback:"💧 שומר עם אצבע בבור? זו עבודה לכל החיים..."}],explanation:"בורות מים טויחו כדי למנוע חלחול של המים אל הסלע."},
      {text:"איזה מים נאספו בדרך כלל בבור?",answers:[{text:"מי ים",correct:false,feedback:"🌊 מי ים בבור מים? זה היה הופך כל כוס תה לאתגר..."},{text:"מי מעיינות",correct:false,feedback:"💧 מעיינות הם מקור מים מצוין, אבל בור מים נועד בעיקר לאסוף מי גשמים."},{text:"מי נהר",correct:false,feedback:"🏞️ בהרי יהודה אין נהרות שאפשר למלא מהם בורות מים."},{text:"מי גשמים",correct:true,feedback:""}],explanation:"בור המים נועד לאסוף מי גשמים ונגר עילי בעונה הרטובה."},
      {text:"מה אפשר ללמוד מבור מים על החיים בעת העתיקה?",answers:[{text:"שלא היה צורך לתכנן מראש",correct:false,feedback:"💧 דווקא להפך. בור מים הוא הוכחה לכמה חשוב היה לחשוב חודשים קדימה."},{text:"שהגשם ירד כל השנה",correct:false,feedback:"🌧️ הלוואי... אם כך, לא היה צריך להשקיע בבניית בורות מים."},{text:"שהמים היו משאב יקר שדרש תכנון ואגירה",correct:true,feedback:""},{text:"שכל משפחה שתתה רק יין",correct:false,feedback:"🍷 יין היה חשוב, אבל כשצמאים באמת... מים מנצחים."}],explanation:"בור מים מלמד שמים היו משאב יקר, ושחיים בהר דרשו תכנון ואגירה."}
    ],
    beitbad:[
      {text:"מה הפיקו בבית הבד?",answers:[{text:"קמח",correct:false,feedback:"🫒 קמח שייך לדישון ולגורן. זייתון עובד עם זיתים."},{text:"דבש",correct:false,feedback:"🫒 דבש זה טעים, אבל בבית הבד לא רדו דבש."},{text:"שמן זית",correct:true,feedback:""},{text:"יין",correct:false,feedback:"🫒 יין? גתון כבר מטפל בזה."}],explanation:"בבית הבד ריסקו וסחטו זיתים כדי להפיק שמן."},
      {text:"מה קרה לזיתים אחרי שרוסקו?",answers:[{text:"בישלו אותם בסיר גדול",correct:false,feedback:"🫒 זיתים לא הפכו לשמן בגלל מרק טוב."},{text:"ייבשו אותם בשמש",correct:false,feedback:"🫒 שמש יש בשפע, אבל כאן צריך לחץ."},{text:"הכניסו את העיסה לעקלים ולחצו עליה כדי להפיק שמן",correct:true,feedback:""},{text:"ערבבו אותם עם מים כדי להפיק שמן מהר יותר",correct:false,feedback:"🫒 מים לא מקצרים דרך לשמן טוב."}],explanation:"את עיסת הזיתים הכניסו לעקלים ולחצו עליה כדי להוציא את השמן."},
      {text:"למה שימש שמן הזית בעת העתיקה?",answers:[{text:"רק לבישול",correct:false,feedback:"🫒 רק לבישול? שמן הזית היה הרבה יותר עסוק מזה."},{text:"רק להדלקת מנורות",correct:false,feedback:"🫒 אור זה חשוב, אבל שמן הזית עשה עוד כמה עבודות."},{text:"למאכל, להדלקה, לרפואה, למשיחה ולפולחן",correct:true,feedback:""},{text:"בעיקר לצביעת בגדים",correct:false,feedback:"🫒 בגדים זה נחמד, אבל זה לא היה עיקר הסיפור של שמן הזית."}],explanation:"שמן הזית היה חומר מרכזי למאכל, אור, רפואה, פולחן ומשיחה."},
      {text:"מדוע נחשב עץ הזית לעץ מיוחד כל כך?",answers:[{text:"כי הוא גדל רק בארץ ישראל",correct:false,feedback:"🫒 רגע... ומה עם עצי הזית באיטליה, ספרד, יוון, לבנון ושאר אגן הים התיכון?"},{text:"כי הוא מניב פירות כבר בשנה הראשונה",correct:false,feedback:"🫒 בשנה הראשונה? הלוואי."},{text:"כי הוא מסוגל לחיות מאות שנים ולהמשיך להניב גם לאחר שנפגע",correct:true,feedback:""},{text:"כי אי אפשר לכרות אותו",correct:false,feedback:"🪓 הלוואי שאי אפשר היה לכרות עץ זית..."}],explanation:"עצי זית יכולים לחיות מאות שנים, ולעיתים להמשיך להתחדש גם אחרי פגיעה קשה."}
    ],
    tatzpit:[
      {text:"ביום עם ראות טובה במיוחד, עד לאן ניתן לראות מכאן?",answers:[{text:"הרי חברון",correct:false,feedback:"🌬️ הרי חברון בכיוון אחר. אווירון מבקש להסתכל מערבה."},{text:"הרי הגליל",correct:false,feedback:"🌬️ אופטימיות זה חשוב... אבל לא עד כדי כך."},{text:"הים התיכון",correct:true,feedback:""},{text:"הרי אדום",correct:false,feedback:"🌬️ בשביל הרי אדום צריך להסתובב בערך 180 מעלות."}],explanation:"בימים בהירים במיוחד ניתן לראות מכאן מערבה עד הים התיכון."},
      {text:"מה מאפיין את הרי ירושלים לעומת מישור החוף?",answers:[{text:"הם עשויים בעיקר מבזלת",correct:false,feedback:"🌬️ בזלת? זה כבר נשמע יותר כמו רמת הגולן."},{text:"הם עשויים בעיקר מאבן גיר, ולכן יש בהם מערות ובורות מים",correct:true,feedback:""},{text:"הם בנויים בעיקר מדיונות חול",correct:false,feedback:"🌬️ דיונות? זה נשמע כמו חוף, לא כמו הרי ירושלים."},{text:"הם נוצרו מהתפרצויות געשיות",correct:false,feedback:"🌬️ הרי ירושלים מרשימים, אבל לא בגלל הרי געש."}],explanation:"אבן הגיר של הרי ירושלים מאפשרת חציבה של מערות, מקוואות ובורות מים."},
      {text:"מכאן מתחיל המעבר החשוב מהשפלה אל...",answers:[{text:"אילת",correct:false,feedback:"🌬️ אילת תחכה לטיול אחר."},{text:"ירושלים",correct:true,feedback:""},{text:"בקעת הירדן",correct:false,feedback:"🌬️ בקעת הירדן נמצאת בסיפור אחר של הארץ."},{text:"החרמון",correct:false,feedback:"🌬️ אם הגעתם לחרמון, כנראה שהרמז הבא היה ממש לא ברור."}],explanation:"האזור יושב על ציר העלייה מן השפלה אל הרי ירושלים."},
      {text:"העמק שניבט ממערב נקרא עמק איילון. במה הוא מוכר במיוחד?",answers:[{text:"כהשראה לשם של אילון",correct:true,feedback:""},{text:"כמקום שבו גידלו בעיקר אורז",correct:false,feedback:"🌬️ אורז בעמק איילון? אווירון מרים גבה."},{text:"כגבול הדרומי של החרמון",correct:false,feedback:"🌬️ החרמון רחוק מכאן יותר מכמה נשימות הרים."},{text:"כמפרץ ימי עמוק",correct:false,feedback:"🌬️ מפרץ ימי? אם יש כאן ים, מישהו שכח לעדכן את המפה."}],explanation:"עמק איילון הוא אחד המרחבים הבולטים הנראים מן התצפית מערבה."}
    ]
  }
};
// MVP French: UI fully translated. Questions fall back to Hebrew if fr questions are not yet curated.
QUESTIONS.fr = QUESTIONS.he;
